// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAEXxgDMIFzPwCUqkwpyHnzMPe50FWcKI',
    appId: '1:275304988180:web:4d9ccde8cb120ced227101',
    messagingSenderId: '275304988180',
    projectId: 'pricetracker-8b132',
    authDomain: 'pricetracker-8b132.firebaseapp.com',
    storageBucket: 'pricetracker-8b132.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItY2LhtFhOYCDR9Xi0Kg9ZrTWG14_1IA',
    appId: '1:275304988180:android:d59d25506b9d7f77227101',
    messagingSenderId: '275304988180',
    projectId: 'pricetracker-8b132',
    storageBucket: 'pricetracker-8b132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6P-7aXhltbQGBP3ar9ZvMbrgqBy9vDds',
    appId: '1:275304988180:ios:6d66da2192441457227101',
    messagingSenderId: '275304988180',
    projectId: 'pricetracker-8b132',
    storageBucket: 'pricetracker-8b132.firebasestorage.app',
    iosBundleId: 'com.example.priceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6P-7aXhltbQGBP3ar9ZvMbrgqBy9vDds',
    appId: '1:275304988180:ios:6d66da2192441457227101',
    messagingSenderId: '275304988180',
    projectId: 'pricetracker-8b132',
    storageBucket: 'pricetracker-8b132.firebasestorage.app',
    iosBundleId: 'com.example.priceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAEXxgDMIFzPwCUqkwpyHnzMPe50FWcKI',
    appId: '1:275304988180:web:23725313ce604367227101',
    messagingSenderId: '275304988180',
    projectId: 'pricetracker-8b132',
    authDomain: 'pricetracker-8b132.firebaseapp.com',
    storageBucket: 'pricetracker-8b132.firebasestorage.app',
  );
}
